language: go

matrix:
  include:
    - os: linux
      go: tip
    - os: osx
      go: tip
    - os: windows
      go: 1.12.4

services:
  - docker

before_install:
  - go get github.com/logrusorgru/aurora

script:

  - docker build -t commoncrawler .