language: go

go:
  - tip

os:
  - osx
  - linux
  - windows

before_install:
  - go get github.com/logrusorgru/aurora

script:

  - go build src/*.go
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./analyze;          fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./analyze;        fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./analyze.exe;  fi