language: go

matrix:
  include:
    - os: linux
      go: tip
    - os: osx
      go: tip
    - os: windows
      go: 1.12.4

services:
  - docker

before_install:
  - go get github.com/logrusorgru/aurora

script:

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then go run src/*.go;                    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t commoncrawler .;  fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then docker build -t commoncrawler .;  fi